### ISSUE TITLE
api v2 authentication

### ISSUE THREAD

**Issue by jsveto** [Kucoin/kucoin-api-docs#1]
Hi i am having troubles authenticating with api v2. I can't get past error:

400001 | Any of KC-API-KEY, KC-API-SIGN, KC-API-TIMESTAMP, KC-API-PASSPHRASE is missing in your request header
-- | --

Header fields are there (i checked with wireshark):

GET /api/v1/accounts HTTP/1.1
Host: openapi-v2.kucoin.com
Accept: */*
Content-Type: application/json
KC-API-KEY: xxxxxxxxxxxxxxxx
KC-API-SIGN: qNgz7z3f9RtACh/f2hEKuydwpGnHsLgxZWZSVUBNpss=
KC-API-TIMESTAMP: 2019-02-18T21:32:29.824Z
KC-API-PASSPHRASE: yyyyyyyyy

I also tried TIMESTAMP with milliseconds. Is there any special order that needs to be followed for header parameters?

Regards,
jsveto

**Comment by cryptonotifier** [comment]
Timestamp should be milliseconds (numeric) from 1.1.1970. The order is OK

**Comment by jsveto** [comment]
Indeed it was problem with timestamp format. Thanks for your help. However i would expect following error:


400002 | KC-API-TIMESTAMP Invalid -- Time differs from server time by more than 5 seconds
-- | --


Nevertheless, i am up and running. Thank you for your help.

Regards,
jsveto
