### ISSUE TITLE
Cannot get all open orders

### ISSUE THREAD

**Issue by jankopovolny** [Kucoin/kucoin-api-docs#10]
When trying to use endpoint:
var endpoint = $"/api/v1/orders";

I get only trades I opened in last 24 hours.

When I try to use parameters "startAt" and "endAt" none trades are received from response.

There is no error, Data is null.

**Comment by purekid** [comment]
Add "status" parameter-------- 原始邮件 --------主题：[Kucoin/kucoin-api-docs] Cannot get all open orders (#10)发件人：jankopovolny 收件人：Kucoin/kucoin-api-docs 抄送：Subscribed When trying to use endpoint:
var endpoint = $"/api/v1/orders";
I get only trades I opened in last 24 hours.
When I try to use parameters "startAt" and "endAt" none trades are received from response.
There is no error, Data is null.

**Comment by jankopovolny** [comment]
Hi Thanks for reply.
I added status: active.
 var orders = _service.GetOrders("GRIN-ETH", OrderStatus.ACTIVE).Result;
I'm getting only trades posted in last 24h, that is one trade, but I got 3 trades active in total.

**Comment by purekid** [comment]
When you query "active" orders, will return all orders.
