### ISSUE TITLE
Cancel All orders - symbol not working.

### ISSUE THREAD

**Issue by DeltaBalances** [Kucoin/kucoin-api-docs#11]
The function to [cancel all orders](https://docs.kucoin.com/#cancel-all-orders) seems to ignore the optional parameter.

**Cancel all orders: DELETE /api/v1/orders**

| Param  | Type   | Description                                              |
|--------|--------|----------------------------------------------------------|
| symbol | string | [optional] Only cancel orders open for a specific symbol |

**Scenario**

1.  I place an order to buy on 'BTC-USDT'.
This returns orderId `5c723xxxxxxxxxxx`.
2. This order shows up as active on both the Kucoin website and API
3. I call **DELETE /api/v1/orders** with symbol parameter 'ETH-BTC', a different market.
This signs a signature like `"1550988726892DELETE/api/v1/orders{"symbol":"ETH-BTC"}"`
I get the response 
```
{
   "cancelledOrderIds": [
    "5c723xxxxxxxxxxx"
   ]
}
```
4. Cancel all orders with symbol ; 'ETH-BTC', just cancelled my 'BTC-USDT' order.
This even works if I set `symbol` to a random string like `{"symbol":"FooBar"}`.

**Suggestion**

If a symbol is included, any order not matching that symbol should stay active.

**Comment by purekid** [comment]
Hi, the parameter of DELETE should be included in query string, like:
DELETE /api/v1/orders?symbol=ETH-BTC  .  This is more in line with the HTTP
protocol specification.

**Comment by DeltaBalances** [comment]
Thanks!
My mistake, handling DELETE parameters more like a GET request fixed my issue.

To avoid others bothering you in the future, you could update this sentence [here](https://docs.kucoin.com/#signing-a-message)
> For **GET** request, the **requestEndpoint** needs to contain the query string. 

> For **GET**  and **DELETE** requests, the **requestEndpoint** needs to contain the query string.
