### ISSUE TITLE
Trade history includes wrong orders

### ISSUE THREAD

**Issue by rdbr** [Kucoin/kucoin-api-docs#118]
The website https://www.kucoin.com/order/deal-detail and the API `/api/v1/fills` return wrong orders. It shows the correct fills, but also shows empty/canceled orders which should have been filtered out.

**Comment by dangth92** [comment]
Yes, I also have the same issue. It just happen from May 22.

**Comment by ReetaZhang** [comment]
> The website https://www.kucoin.com/order/deal-detail and the API `/api/v1/fills` return wrong orders. It shows the correct fills, but also shows empty/canceled orders which should have been filtered out.

Yep, we are trying to fix this issue and filter this kind of data. Today we will update to fix this issue.
