### ISSUE TITLE
Candles API always return empty data

### ISSUE THREAD

**Issue by iamamyth** [Kucoin/kucoin-api-docs#125]
It seems the /api/v1/market/candles API returns an empty data set for all markets (tried GRIN-BTC, GRIN-LTC), regardless of timeframe (startAt/endAt) or type (tested 1min, 5min, 15min, 1hour).

**Comment by ReetaZhang** [comment]
https://docs.kucoin.com/#get-klines  give me your request parameters

**Comment by learnathoner** [comment]
Hi, also getting the same error for every query, including the official example in the guide: `/api/v1/market/candles?type=1min&symbol=BTC-USDT` returns `{"code":"200000","data":[]}`

**Comment by ReetaZhang** [comment]
Hey, u need to specify the two params: endAt and startAt

**Comment by ReetaZhang** [comment]
if not, the default value is 0

**Comment by ReetaZhang** [comment]
https://api.kucoin.com/api/v1/market/candles?type=1min&symbol=BTC-USDT&startAt=1566703297&endAt=1566789757 like this

**Comment by dattran2346** [comment]
> if not, the default value is 0

Hi @ReetaZhang 
I also have the same problem when querying without startAt and endAt param. IMHO this should be included in the official document.
