### ISSUE TITLE
Websocket sends duplicate level 3 OPEN messages

### ISSUE THREAD

**Issue by augenblicke** [Kucoin/kucoin-api-docs#135]
Very frequently websocket sends a bunch of duplicate OPEN messages like below (not only for KCS-ETH), these messages differ only by sequence...

What does this mean? How an order with the same id can be opened several times?

{"sequence":"1556385123826","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123828","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123830","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123834","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123836","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123838","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123840","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123842","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123844","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123846","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123848","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123850","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123852","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123854","symbol":"KCS-ETH","side":"sell","size":"300.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}
{"sequence":"1556385123856","symbol":"KCS-ETH","side":"sell","size":"200.00000000000000000000","orderId":"5d5584d04c06876f0653ec63","price":"0.00897070000000000000","time":"1565885725471463222","type":"open"}

**Comment by ReetaZhang** [comment]
Hello

**Comment by ReetaZhang** [comment]
This order is a kind of special order, for instance, the iceberg order.
So those are not the duplicate open msg from Level-3 with totally different sequences.
