### ISSUE TITLE
Trade History Not Coming Through

### ISSUE THREAD

**Issue by cgunnels** [Kucoin/kucoin-api-docs#14]
I'm trying to get the trade history for a user via https://docs.kucoin.com/#list-fills

I've checked the user's account via the website and they have 30 trades back in Jan of 2018. I've sent the following requests all coming back with:
```
{
    "code": "200000",
    "data": {
        "totalNum": 0,
        "totalPage": 0,
        "pageSize": 50,
        "currentPage": 1,
        "items": []
    }
}
```
Requests sent to (All requests have correct headers or API would respond accordingly):
https://openapi-v2.kucoin.com/api/v1/fills?symbol=KCS-BTC&startAt=0
https://openapi-v2.kucoin.com/api/v1/fills?startAt=0000000000000
https://openapi-v2.kucoin.com/api/v1/fills?symbol=KCS-BTC&startAt=1515110400000
https://openapi-v2.kucoin.com/api/v1/fills?symbol=ETH-BTC&startAt=0

**Comment by purekid** [comment]
The current list-fills interface can only query the 24-hour interval for each request.  
The default is to query the lastest 24 hours.

**Comment by cgunnels** [comment]
Yes, I saw that on another issue so I added an endAt param as well and it didn't work.
startAt = 1516752000000
endAt = 1516838399000

**Comment by mchalise** [comment]
@cgunnels  Did you find any solution? I am also stuck with the same issue.

**Comment by cgunnels** [comment]
> @cgunnels Did you find any solution? I am also stuck with the same issue.

No, I found out that they shut down API access to data before Jan 2019. If you want data before Jan 2019 you have to download it to csv from their UI.
