### ISSUE TITLE
Active orders not fetched correctly

### ISSUE THREAD

**Issue by raytroy** [Kucoin/kucoin-api-docs#15]
I am trying to access ALL active orders (orders still on the order book) using the /api/v1/orders endpoint.

I have sent all the requests with {"status":"active"} but the results are for the {"status":"done"} which is the default (see below).

I have double checked with the user interface on the website and the orders are open.

When I check the status of one of the open orders using the /api/v1/orders/order-id the status is "active".

The documentation states "Orders which are resting on the order book, will be marked with the **active** status. Orders which are no longer resting on the order book, will be marked with the **done** status.

For order checking, after inputting the correct parameters, you could check the orders in all status. But if the status parameter is not input into the orders interface, the system would return the orders of done status to you by default."

**Comment by purekid** [comment]
Hi raytroy.  List orders is a GET endpoint, so you should send parameters like  /api/v1/orders?status=active.
