### ISSUE TITLE
Fills endpoint does not return first trade for given symbol.

### ISSUE THREAD

**Issue by kevinstl** [Kucoin/kucoin-api-docs#152]
When I call the https://docs.kucoin.com/#list-fills endpoint it does not return the first trade for a given currency.

For example if I've only executed one limit buy for SNT with BTC I receive no trade history.

If I've executed 4 limit buys for SNT with BTC I receive the last 3 trade records.

I've repeated this issue for multiple currency pairs.

**Comment by ReetaZhang** [comment]
Hello
Could u provide the request parameters and the orderId?
