### ISSUE TITLE
WebSocket Error: getaddrinfo ENOTFOUND push1-v2.kucoin.com

### ISSUE THREAD

**Issue by bugs181** [Kucoin/kucoin-api-docs#159]
According to the docs, I'm attempting to connect to the correct URL. I know that the base URL has been updated and not sure if this is what's causing my issue. It's been a few months since I've worked with this particular exchange, however it was working fine last time I checked.

The full URLs I'm using are as follows.

Live:
wss://push1-v2.kucoin.com/endpoint?token=${token}&[connectId=${Date.now()}]

Sandbox:
wss://push1-sandbox.kucoin.com/endpoint?token=${token}&[connectId=${Date.now()}]

**Comment by ReetaZhang** [comment]
Hello, you should get the endpoint of the WebSocket before you create the connection.
![image](https://user-images.githubusercontent.com/40235970/72308613-c88fbe00-36b7-11ea-8049-d22e3dfe26cc.png)
