### ISSUE TITLE
Clarification request: General Logic for Message Judgement in Client Side

### ISSUE THREAD

**Issue by jayarjo** [Kucoin/kucoin-api-docs#172]
[General Logic for Message Judgement in Client Side](https://docs.kucoin.com/#general-logic-for-message-judgement-in-client-side) states:

> 1.Judge message type. There are three types of messages at present: message (the commonly used messages for push), notice (the notices generally used), and command (consecutive command).

But it seems there's only one type `message`. At least I've not seen types `notice` or `command` mentioned anywhere. Can you either elaborate or fix that portion of the doc?

**Comment by ReetaZhang** [comment]
![image](https://user-images.githubusercontent.com/40235970/78881481-762d2600-7a89-11ea-8ef6-152a402bcce3.png)
