### ISSUE TITLE
Wrong behavior of the opened order

### ISSUE THREAD

**Issue by alinaKava** [Kucoin/kucoin-api-docs#187]
Hi. 
I get the list of orders with one active order and then cancel this order by id (the exchange returns 200000, that means - everything is ok). But this order is not canceled - request returns this order as active again. Moreover, there is no order as active via the web interface. So, my order with id 5ea95a17227e210009d33317 exists only by Rest request approximately 10 hours, I can't cancel it because it is not actually opened.

**Comment by ReetaZhang** [comment]
Hello,
We are optimizing this feature and will release it this week.
