### ISSUE TITLE
Duplicated websocket messages at any balance change

### ISSUE THREAD

**Issue by augenblicke** [Kucoin/kucoin-api-docs#188]
After websocket upgrade at april 13 server started to send duplicate messages on every balance change

It sends 7 fully equal messages on any balance change

Why?

**Comment by augenblicke** [comment]
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}

**Comment by ReetaZhang** [comment]
Hello, could you provide the topic of the message?

**Comment by augenblicke** [comment]
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}
{"accountId":"7c4a8fea00a3e8173d4eb6a3","total":"373877.01908065","holdChange":"373877","relationEvent":"trade.hold","available":"0.01908065","currency":"ACAT","availableChange":"-373877","time":"1587042256861","hold":"373877","relationEventId":"5e4857d0dmf79a000143t0a5"}

**Comment by augenblicke** [comment]
of course, topic: /account/balance

**Comment by augenblicke** [comment]
issue has been solved now
