### ISSUE TITLE
/market/level2 updates with zero price

### ISSUE THREAD

**Issue by asavis** [Kucoin/kucoin-api-docs#19]
I see a lot of updates like:

{"data":{"sequenceStart":1550467687716,"symbol":"BTC-USDT","changes":{"asks":[["0","0","1550467687716"]],"bids":[]},"sequenceEnd":1550467687716},"subject":"trade.l2update","topic":"/market/level2:BTC-USDT","type":"message"}

As you see the price is zero. It makes no sense. It seems you send such update for every trade but the message has absolutely no usable information.

**Comment by purekid** [comment]
This situation is due to the event that the seq sequence t is changed inside the engine, and is pushed to the outside for calibration of the sequence.

**Comment by asavis** [comment]
I think you need to find a better solution. You push too much fake data just to update the seq that does not seems to change for an external data consumer.

**Comment by purekid** [comment]
We will have an update plan for this

**Comment by proxychainio** [comment]
It's still there after 3 months. kucoin is almost dead...
