### ISSUE TITLE
Get All Tickers missing Bid and Ask

### ISSUE THREAD

**Issue by feltkamptv** [Kucoin/kucoin-api-docs#2]
The previous API (v1) had the endpoint: https://api.kucoin.com/v1/market/open/symbols which would return the current Last, Bid and Ask price for all markets:

```
[
    {
      "coinType": "KCS",
      "trading": true,
      "lastDealPrice": 4500,
      "buy": 4120,
      "sell": 4500,
      "coinTypePair": "BTC",
      "sort": 0,
      "feeRate": 0.001,
      "volValue": 324866889,
      "high": 6890,
      "datetime": 1506051488000,
      "vol": 5363831663913,
      "low": 4500,
      "changeRate": -0.3431
    },...
```

The new endpoint: https://openapi-v2.kucoin.com/api/v1/market/allTickers does only return a close value, but not the Bid and Ask prices (buy and sell)... 
```
[{
	"symbol": "LOOM-BTC",
	"high": "0.00001212",
	"vol": "4706.7114",
	"low": "0.00001109",
	"changePrice": "-0.00000064",
	"changeRate": "-0.0545",
	"close": "0.00001109",
	"volValue": "0.055227432084",
	"open": "0.00001173"
},...
]
```

To now achieve the same result, we have to do a call for each market to get the Bid and Ask prices with the tickers. Or am I missing something? If not, could you please add this again to the API?

**Comment by MarcelBeining** [comment]
Also it does not return the fees anymore! How can one now get info about the trading fee? Could not find it in the docs, but is crucial!

**Comment by feltkamptv** [comment]
Correct! It used to had **feeRate** in it, which is gone now. It seems that at the moment trading fees cannot be retrieved programmatically with the API at all. 👎

**Comment by feltkamptv** [comment]
So KuCoin just changed the API, now the output of AllTickers is:

```
[{
	"symbol": "LOOM-BTC",
	"high": "0.0000123",
	"vol": "44166.1591",
	"last": "0.00001204",
	"low": "0.00001159",
	"buy": "0.0000118",
	"sell": "0.00001188",
	"changePrice": "0.00000017",
	"changeRate": "0.0143"
},...
]

KUCOIN STOP JUST CHANGING APIS!!!!!!!!

**Comment by MarcelBeining** [comment]
unbelievable...

**Comment by purekid** [comment]
The buy and sell fields have been added.

```json
{
        "symbol": "BCD-BTC",
        "buy": "0.00018564",
        "sell": "0.0002",
        "changeRate": "-0.0753",
        "changePrice": "-0.00001522",
        "high": "0.00021489",
        "low": "0.00018351",
        "vol": "72.99679763",
        "last": "0.00018664"
      }
```

**Comment by MarcelBeining** [comment]
@purekid Thanks but what about the mentioned "feeRate"? By which endpoint can one get the feeRate of a symbol?
