### ISSUE TITLE
keep getting KC-API-SIGN error 

### ISSUE THREAD

**Issue by jackboo13** [Kucoin/kucoin-api-docs#32]
below here is my code with google appscript(base on javascript) i really have no clue why this keep getting me error,GET method works fine but nothing works with POST method,please help me. Api key and secret key are both correct and without any issue.

function test(){
  var payload={
    'clientOid':"UUID",
    'payAccountId':'pay id',
    'recAccountId':'received id',
    'amount':'1',
  }
  test1('key',secret',payload);
}
function test1(key,secret,payload){
    var api_key = key;
    var api_secret = secret;
    var api_passphrase = "sandbox1234";
    var data = JSON.stringify(payload);
    var url = 'https://openapi-sandbox.kucoin.com/api/v1/accounts/inner-transfer';
    var now = '' + Date.parse(new Date());
  var str_to_sign = String(now) + 'POST' + '/api/v1/accounts/inner-transfer'+data;
    Logger.log(str_to_sign);
    var signature = Utilities.base64Encode(
        Utilities.computeHmacSignature(Utilities.MacAlgorithm.HMAC_SHA_256, str_to_sign, api_secret))
    var headers = {
        "KC-API-SIGN": signature,
        "KC-API-TIMESTAMP": String(now),
        "KC-API-KEY": api_key,
        "KC-API-PASSPHRASE": api_passphrase,
    }
    var option = {
     "Content-Type": "application/json",
     'method'  : 'post',
     'headers' : headers,
     'payload' : data,
    }
    Logger.log(option);
    response = UrlFetchApp.fetch(url, option);
    Logger.log(response.getContentText());
    }
error code 
{"code":"400005","msg":"Invalid KC-API-SIGN"}

**Comment by bulkaeu** [comment]
Hi,

had the same issue.

I've avoided it by replacing "js-sha256" with "crypto-js" and it's conversion to Base64

import CryptoJS from "crypto-js";

let signature = CryptoJS["HmacSHA256"](strForSign, keys.secret).toString(CryptoJS.enc["Base64"]);

**Comment by jackboo13** [comment]
Apparently in GAS "Content-Type": "application/json" should write like this 'contentType':'application/json' 
final code look like this :
function test(){
  var payload={
    "payAccountId":"5c7b6cdfef83c7378d141fae",
    "recAccountId":"5c7b6d0fef83c7378d14200d"
    ,"amount":"1","clientOid":"UUID"
  };
  test1('key','secret',payload);
}
function test1(key,secret,payload){
    var api_key = key;
    var api_secret = secret;
    var api_passphrase = "sandbox1234";
    var data = JSON.stringify(payload);
    Logger.log(data);
    var url = 'https://openapi-sandbox.kucoin.com/api/v1/accounts/inner-transfer';
    var now = String((new Date()).getTime());
    var str_to_sign = now + 'POST/api/v1/accounts/inner-transfer';
    Logger.log(str_to_sign);
    var signature = Utilities.base64Encode(
        Utilities.computeHmacSignature(Utilities.MacAlgorithm.HMAC_SHA_256, str_to_sign+data, api_secret));
    Logger.log(str_to_sign+data);
    var headers = {
        "KC-API-SIGN": signature,
        "KC-API-TIMESTAMP": now,
        "KC-API-KEY": api_key,
        "KC-API-PASSPHRASE": api_passphrase,
    }
    var option = {
     'contentType':'application/json',
     'method'  : 'POST',
     'headers' : headers,
     'payload' : data,
    }
    Logger.log(option);
    var response = UrlFetchApp.fetch(url, option);
    Logger.log(response);
    }
