### ISSUE TITLE
Time field of websocket Match Execution

### ISSUE THREAD

**Issue by vslee** [Kucoin/kucoin-api-docs#33]
The time field of the websocket Match Execution appears to be different in the 2.0 version of the API. The  2.0 example shows:
"time":"1545913818099033203" which is much longer than in 1.0, where it was:
"time": 1541034625000. It used to be Unix milliseconds. 
The API docs don't specify what it is now in 2.0.
Is it Unix nanoseconds?

**Comment by mingyangwang** [comment]
match and order system use nanoseconds

**Comment by vslee** [comment]
Good to know. Would be helpful for others if the API doc also has this info.
