### ISSUE TITLE
BUG Market Order with BASE price Higher Than Quote Currency Price

### ISSUE THREAD

**Issue by gusaul** [Kucoin/kucoin-api-docs#333]
Create Market Order using `/api/v1/orders` with parameter
```
{
	"clientOid": "e41628ef-58fc-46bb-b06e-a8f5c1ac24a7",
	"side": "buy",
	"symbol": "TRX-USDT",
	"type": "market",
	"tradeType": "TRADE",
	"size": "32.57684"
}
```

since size is should be amount of BASE currency
expected result is I will buy TRX with the amount of `32.57684` USDT
but the actual result is buy TRX with the amount of `32.57684` TRX

This issue is only happen when price of BASE currency is higher than quote, which in this case is USDT > TRX, when I tried buy ETH-USDT (USDT < ETH), the actual result is correct as expected.

Please Help give Clarity, does it expected to behave this way?

**Comment by gusaul** [comment]
@ReetaZhang @codewc

**Comment by Crynetomega** [comment]
The base currency on TRX, the quote currency is USDT. The size is always the base currency.

**Comment by gusaul** [comment]
@Crynetomega no man, I will make it clear
buy TRX-USDT, size is considered as TRX
buy ETH-USDT, size is considered as USDT

those should be both USDT or both not USDT, it must be consistent.

I also observed the same situation on another pair with KCS, if the quote price is lower than base price.

**Comment by gusaul** [comment]
closed, its misunderstood because place order with amount more than available amount is considered as order 100%
