### ISSUE TITLE
Problems to create DepositAddress on non default CHAIN

### ISSUE THREAD

**Issue by caioformiga** [Kucoin/kucoin-api-docs#341]
It's possible to check all available CURRENCY - CHAIN using the ENDPOINT for Currency Details.

Some currencies suports multiple CHAIN, such  as:
For BTC currency: [link](https://api.kucoin.com/api/v2/currencies/BTC) 4 chains
For ETH currency: [link](https://api.kucoin.com/api/v2/currencies/BTC) 3 chains
For USDT currency: [link](https://api.kucoin.com/api/v2/currencies/USDT) 5 chains

Other are 1-to-1 related:
For DOGE currency: [link](https://api.kucoin.com/api/v2/currencies/ETH)
For KLV currency: [link](https://api.kucoin.com/api/v2/currencies/KLV)

***

I need to create a deposit address for a CURRENCY at all CHAINS available or at a specifit CHAIN.

I'm using ENDPOINT v1 to create a DepositAddress (https://docs.kucoin.com/#create-deposit-address) and using as parameters **currency** and **chain**

Bellow a summary of each try:
A) BTC tests
"currency":"BTC";"chain":"BTC"     -> return ok

"currency":"BTC";"chain":"KCC"     -> return error

"currency":"BTC";"chain":"TRC20"     -> return error

"currency":"BTC";"chain":"TRC20"     -> return error

B) ETH tests
"currency":"ETH";"chain":"ERC20"     -> return ok

"currency":"BTC";"chain":"KCC"     -> return error

"currency":"BTC";"chain":"TRC20"     -> return error

The error msg is the same:
{
  "code":"900014",
  "msg":"Invalid chainId"
 }

The API_KEY i'm using works right, it creates for **BTC - BTC** and **ETH** - **ERC20**.
For instance, this API_KEY has all tree permissions: **General, Trade and Transfer**

Where is the problem?

**Comment by caioformiga** [comment]
Using another account, I had success creating a DepositAddress on **EXCHANGE WEB page** see imagem bellow

![screenshot_from_2021-12-10_12-41-04](https://user-images.githubusercontent.com/2387851/145606837-5b905b88-c6b7-4b4f-af60-0e4e3e9b624a.png)

Debuging the page, the ENDPOINT used is: [link](https://www.kucoin.com/_api/currency/currency/chain-info)

Where there is a JSON with chainName and chain property. 
I mapped the each entry, using the key (currency-chainName) to a value chain.

For exemple: 
"currency":"BTC";"chain":"BTC" -> key = [BTC-BTC]; value = btc
"currency":"BTC";"chain":"KCC" -> key = [BTC-KCC]; value = kcc

Using the currency and value (btc, kcc) the ENDPOINT, create deposit address works!

**Comment by astr009neer** [comment]
Struggled a lot yesterday until I found your issue. I am quite surprised that the mapping is not officially documented. Thank you! @caioformiga

**Comment by RenatoExpert** [comment]
Thank you very much, I had a lot of headache until found this JSON. I had problems on withdraw...

**Comment by caioformiga** [comment]
Spreading the word!
Sharing the code!

**Comment by Wayruha** [comment]
Such a bad API documentation and design:(

**Comment by RenatoExpert** [comment]
@Wayruha Its open source, if you feel a lack of something, just make a pull request.
