### ISSUE TITLE
Documentation Missing Error Codes

### ISSUE THREAD

**Issue by kuklaph** [Kucoin/kucoin-api-docs#342]
Hello. There are error codes that are not listed on the Kucoin documentation. For instance { code: '300000', msg: 'Order funds invalid.' } is not found in the documentation. Why is this missing? How many other codes are not listed there?

**Comment by domenicoferraro** [comment]
I've got this too `{ code: '300000', msg: 'Order funds invalid.' }`: what does it mean?
