### ISSUE TITLE
Create deposit wallet sometimes return Invalid request ip

### ISSUE THREAD

**Issue by congminh090800** [Kucoin/kucoin-api-docs#395]
```
  request: { host: 'api.kucoin.com' },
  response: {
    status: 403,
    statusText: 'Forbidden',
    config: { url: '/api/v2/deposit-addresses', method: 'get' },
    data: '{"code":"400006","msg":"Invalid request ip"}'
  }
 ```
 Eventhough I didn't exceed the api limit, Sometimes it still give me this error (sometimes it return data normally).

**Comment by congminh090800** [comment]
its okay now, i had to turn on my vpn

**Comment by yilmaz2434** [comment]
C# kullanıyorum api sürüm 1.0.0.0 2 ye yükselmiş ben yükseltemiyorum kod dosyasına giremiyorum yardım eden olursa sevinirim birde api ye yatırdığımız parayı nasıl geri çekebiliriz
