### ISSUE TITLE
Get List Fills doesn't support get fills in a large timespan (> 24 hours)

### ISSUE THREAD

**Issue by dangth92** [Kucoin/kucoin-api-docs#4]
I tried to get list fills with request parameters:
- startAt = 1550595600000
- endAt = 1550768399000

The reponse content is a message "Get List Fills doesn't support get fills in a large timespan (> 24 hours)" with code "400100"

**Comment by purekid** [comment]
The current query range can only be one day(86400 seconds), and we will provide a larger time range later.

**Comment by cgunnels** [comment]
I tried https://openapi-v2.kucoin.com/api/v1/fills?startAt=1516752000000&endAt=1516838399000 and got back:
```
{
    "code": "200000",
    "data": {
        "totalNum": 0,
        "totalPage": 0,
        "pageSize": 50,
        "currentPage": 1,
        "items": []
    }
}
```
I checked the trading account and there were trades made on the 24th of Jan 2018.
