### ISSUE TITLE
Order book corruption: sequence numbers are skipped by websocket

### ISSUE THREAD

**Issue by benruijl** [Kucoin/kucoin-api-docs#44]
On KCS-BTC the sequence ids from level2 updates went from 1550468120937 to 1550468120940. We have a strong indication that actual changes happened to the order book that were not broadcast to the websocket.

Could you please fix this asap?

```
{"changes":{"asks":[],"bids":[["0","0","1550468120937"]]},"seq":null,"sequenceEnd":1550468120937,"sequenceStart":1550468120937,"symbol":"KCS-BTC","topic":"/market/level2:KCS-BTC"}
{"changes":{"asks":[],"bids":[["0.00014209","1577.26163226","1550468120940"]]},"seq":null,"sequenceEnd":1550468120940,"sequenceStart":1550468120940,"symbol":"KCS-BTC","topic":"/market/level2:KCS-BTC"}
```

**Comment by escwdev** [comment]
I've now noticed this, or a similar issue, on KCS-USDT and recently on EOS-ETH. This did not seem to be happening until late last week based on my used of the lvl2 websocket feed for a wide variety of symbols since the release of API v2.

**Comment by benruijl** [comment]
This could be caused by the fix of bug #21. Perhaps the filtering is now too aggressive.

It is happening quite often. Sometimes every few minutes...

**Comment by nuts-york** [comment]
丢掉

**Comment by nuts-york** [comment]
Occasionally, a message will be dropped. If the client is slow to receive a message in a websocket link, the server TCP link will drop the message sent to the link. If the sequence is found to be discontinuous, you can restructure the OrderBook and get all the information about the OrderBook (including changes to the discarded message).

**Comment by benruijl** [comment]
This is happening very frequently now and it wasn't before. I am certain there is no queue building up on my end.

**Comment by nuts-york** [comment]
Which trade are you using? When did it happen? This information helps us pinpoint specific problems.

**Comment by nuts-york** [comment]
> This is happening very frequently now and it wasn't before. I am certain there is no queue building up on my end.

Hello, where is your service machine located？

**Comment by escwdev** [comment]
For me this is most notable on KCS-USDT with occasional occurrences on other symbols. I've compensated by doing similar to the above and re-initiating the orderbook with a REST call but it is a less than ideal solution.

**Comment by binares** [comment]
And it is corrupting the orderbook:
```
{'sequenceStart': 1553507863439, 'symbol': 'ETH-BTC', 'changes': {'asks': [['0.034414', '0.0247268', '1553507863439']], 'bids': []}, 'sequenceEnd': 1553507863439}
{'sequenceStart': 1553507863440, 'symbol': 'ETH-BTC', 'changes': {'asks': [['0.034414', '0.0123634', '1553507863440']], 'bids': []}, 'sequenceEnd': 1553507863440}
{'sequenceStart': 1553507863442, 'symbol': 'ETH-BTC', 'changes': {'asks': [], 'bids': [['0', '0', '1553507863442']]}, 'sequenceEnd': 1553507863442}
{'sequenceStart': 1553507863443, 'symbol': 'ETH-BTC', 'changes': {'asks': [], 'bids': [['0.034414', '8.1349235', '1553507863443']]}
{'sequenceStart': 1553507863444, 'symbol': 'ETH-BTC', 'changes': {'asks': [], 'bids': [['0.034306', '0', '1553507863444']]}
```
