### ISSUE TITLE
How to Fetch my Trade / Order history via API.

### ISSUE THREAD

**Issue by mchalise** [Kucoin/kucoin-api-docs#45]
I have done some trade after v2 upgrade. I am currently trying **GET /orders** and **GET /fills**  but its returning empty data. My API keys and connection is correct BTW as i was able to fetch by deposits and withdrawals.

**Comment by mchalise** [comment]
Found the answer.

**Comment by miller46** [comment]
What the hell bro share the answer

**Comment by mchalise** [comment]
@miller46 I used. 

> "/accounts", 'GET'

to fetch Account ID's of TYPE="Trade" and CODE="200000"  see doc for this.

> /accounts/#{id}/ledgers?currentPage=#{page}&pageSize=500"

Is used to fetch Order ID 

> fills?orderId=#{oid}", 'GET'

I haven't seen a lastet doc but 3 months back when the new system was launched this was the process i used. There is a telegram channel for API discussion(Kucoin official) you can use it to communicate with the support team if you have any confusion.

**Comment by idris67** [comment]
Hello @mchalise do you have the code example on how to get the trade history of my trades on kucoin via API please? 
Would be very helpful

**Comment by mchalise** [comment]
Ruby Example: 
```ruby
  BASE_URL = 'https://api.kucoin.com/api/v1'.freeze
  START_TS = 1550657852000.freeze #FEB 20, 2019 v2 release date

  def self.call_kucoin(url, type, data)
      full_url = "#{BASE_URL}#{url}"
      now = (Time.now.to_f * 1000).to_i.to_s
      str_to_sign = now+"#{type}/api/v1#{url}"
      signature = ::Base64.strict_encode64(
        ::OpenSSL::HMAC.digest(
          ::OpenSSL::Digest.new('sha256'),
          data[:api_secret].encode("utf-8"), str_to_sign.encode("utf-8")
          )
        )
      headers = {
        'Accept': 'application/json',
        'KC-API-SIGN': signature,
        'KC-API-TIMESTAMP': now,
        'KC-API-KEY': data[:api_key],
        'KC-API-PASSPHRASE': data[:password]
      }
      resp = HTTParty.get(full_url, headers: headers, format: :json)
      return JSON.parse(resp.body)
  end
```
Now to get Accounts or order details call this:
```ruby 
accounts = call_kucoin("/accounts", 'GET', data)

def self.generated_possible_timestamp
      timestamp_stack = [START_TS]
      timestamp_now = (Time.now.to_f * 1000).to_i
      loop do
        last_timestamp = timestamp_stack.last
        latest_calculated_timestamp = (Time.at(last_timestamp/1000)+1.week).to_i*1000
        break if latest_calculated_timestamp > timestamp_now
        timestamp_stack << latest_calculated_timestamp
      end
      return timestamp_stack      
end
#ts = single timestamp from above. loop through above list and run below method.
order_data = call_kucoin("/fills?currentPage=1&pageSize=500&startAt=#{ts}", 'GET', data)
```
Frankly speaking, I don't like their API flow that much. Too much complexity for simple things. Hope this helps man. @idris67
