### ISSUE TITLE
List of Balances

### ISSUE THREAD

**Issue by ryanfalzon** [Kucoin/kucoin-api-docs#47]
I am currently using the code below to acquire a list of balances for a particular account. However the response I get is an empty list. This is very strange as I am 100% sure that the account I am querying indeed has a balance. has anyone ever encountered this issue? I have only stumbled on this case when updating to the new APIs. With the old APIs everything worked fine.

```c#
string endpoint = "/api/v1/accounts";
long nonce = RequestTools.GetNonce();

using (var client = new HttpClient())
using (var httpRequest = new HttpRequestMessage(new HttpMethod("GET"), endpoint))
{
	client.BaseAddress = new Uri(Properties.Settings.Default.KuCoinUri);

	var message = $"{nonce}GET{endpoint}";
	var signedMessage = "";
	using (var encoder = new HMACSHA256(Encoding.UTF8.GetBytes(request.PrivateKey)))
	{
		var hash = encoder.ComputeHash(Encoding.UTF8.GetBytes(message));
		signedMessage = Convert.ToBase64String(hash);
	}

	httpRequest.Headers.Add("KC-API-KEY", request.PublicKey);
	httpRequest.Headers.Add("KC-API-Timestamp", nonce.ToString());
	httpRequest.Headers.Add("KC-API-SIGN", signedMessage);
	httpRequest.Headers.Add("KC-API-PASSPHRASE", request.Passphrase);

	var response = await client.SendAsync(httpRequest);
	var result = await response.Content.ReadAsStringAsync();
}
```

This is the response I am getting:
![image](https://user-images.githubusercontent.com/30478175/54440374-d80e4580-473a-11e9-8400-efb5eabff43a.png)

**Comment by mingyangwang** [comment]
You need to create an account firstly.

**Comment by ZhangReeta** [comment]
It is literally normal. Because you didn't create the account so the data was empty. 
You can create an account by this /api/v1/accounts.
