### ISSUE TITLE
Unclear level3 engine behaviour

### ISSUE THREAD

**Issue by augenblicke** [Kucoin/kucoin-api-docs#64]
Very often come across the following situation (not only with KCS-BTC):

After RECEIVED msg with orderType="limit" sequence missing for 1 message, this missed msg is definitely OPEN (it will be clear below)
If then request the full level3 book the order id and price (contained in missed msg) will not be in this book

After some time, a MATCH or DONE message arrives with this missed order id (to cancel or match this order), but the book doesn't contain this order id & price!

In such conditions it is impossible to calibrate level3 book properly...

2019.03.27 20:08:39.138       {"data":{"sequence":"1553507769484","symbol":"KCS-BTC","orderType":"limit","side":"buy","size":"11.0508","orderId":"5c9bae17cdaba45ba946195f","price":"0.00032858000000000000","time":"1553706519125155945","type":"received","clientOid":"6ad527a7-de6d-4b6b-b1c6-0dfd85e4ac53"},"subject":"trade.l3received","topic":"/market/level3:KCS-BTC","type":"message"}
--- missed 1 msg with sequence 1553507769485
2019.03.27 20:08:39.342       {"data":{"sequence":"1553507769486","symbol":"KCS-BTC","orderType":"limit","side":"sell","size":"20.0000","orderId":"5c9bae17cdaba45ba946196d","price":"0.00032988000000000000","time":"1553706519321053362","type":"received","clientOid":"8de27cd1-4e7d-4dc6-bb3a-bff7799482d1"},"subject":"trade.l3received","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.342       [1] KCS-BTC book msg sequence missed 1 message (1553507769484 ... 1553507769486), calibration required, requesting full level 3 book
2019.03.27 20:08:39.342       {"data":{"sequence":"1553507769487","symbol":"KCS-BTC","side":"sell","size":"20.0000","orderId":"5c9bae17cdaba45ba946196d","price":"0.00032988000000000000","time":"1553706519321053362","type":"open","remainSize":"20.0000"},"subject":"trade.l3open","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.670       {"data":{"sequence":"1553507769488","symbol":"KCS-BTC","reason":"canceled","side":"sell","size":"987","orderId":"5c9baddf5137b950eb92f450","price":"0.00033050000000000000","time":"1553706519673573025","type":"done"},"subject":"trade.l3done","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.701       {"data":{"sequence":"1553507769489","symbol":"KCS-BTC","reason":"canceled","side":"sell","size":"935","orderId":"5c9bac675137b94c64a5d931","price":"0.00033049000000000000","time":"1553706519694664424","type":"done"},"subject":"trade.l3done","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.764       {"data":{"sequence":"1553507769490","symbol":"KCS-BTC","orderType":"limit","side":"sell","size":"676","orderId":"5c9bae17cdaba4572f6e745d","price":"0.00032990000000000000","time":"1553706519757210114","type":"received","clientOid":"15537065192913"},"subject":"trade.l3received","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.764       {"data":{"sequence":"1553507769491","symbol":"KCS-BTC","side":"sell","size":"676","orderId":"5c9bae17cdaba4572f6e745d","price":"0.00032990000000000000","time":"1553706519757210114","type":"open","remainSize":"676"},"subject":"trade.l3open","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.810       {"data":{"sequence":"1553507769492","symbol":"KCS-BTC","orderType":"limit","side":"sell","size":"674","orderId":"5c9bae175137b950eb92fcc7","price":"0.00033005000000000000","time":"1553706519819064121","type":"received","clientOid":"15537065191184"},"subject":"trade.l3received","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.842       {"data":{"sequence":"1553507769493","symbol":"KCS-BTC","side":"sell","size":"674","orderId":"5c9bae175137b950eb92fcc7","price":"0.00033005000000000000","time":"1553706519819064121","type":"open","remainSize":"674"},"subject":"trade.l3open","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.873       {"data":{"sequence":"1553507769494","symbol":"KCS-BTC","reason":"canceled","side":"buy","size":"62","orderId":"5c9bacc3cdaba4572f6e44be","price":"0.00032844000000000000","time":"1553706519870874089","type":"done"},"subject":"trade.l3done","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.998       {"data":{"sequence":"1553507769495","symbol":"KCS-BTC","orderType":"limit","side":"buy","size":"151","orderId":"5c9bae17c788c664cf0346a2","price":"0.00032804000000000000","time":"1553706519984838156","type":"received","clientOid":"15537065194209"},"subject":"trade.l3received","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:39.998       {"data":{"sequence":"1553507769496","symbol":"KCS-BTC","side":"buy","size":"151","orderId":"5c9bae17c788c664cf0346a2","price":"0.00032804000000000000","time":"1553706519984838156","type":"open","remainSize":"151"},"subject":"trade.l3open","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:41.279       KCS-BTC book successfully calibrated   requested book sequence: 1553507769496
--- book calibrated, but order with id 5c9bae17cdaba45ba946195f is not present in this book, DONE/MATCH messages with this order id also haven't yet come
2019.03.27 20:08:49.732       {"data":{"sequence":"1553507769497","symbol":"KCS-BTC","orderType":"limit","side":"sell","size":"303.0266","orderId":"5c9bae21cdaba45ba9461adb","price":"0.00032924000000000000","time":"1553706529722257392","type":"received"},"subject":"trade.l3received","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:49.732       {"data":{"sequence":"1553507769498","symbol":"KCS-BTC","side":"sell","size":"303.0266","orderId":"5c9bae21cdaba45ba9461adb","price":"0.00032924000000000000","time":"1553706529722257392","type":"open","remainSize":"303.0266"},"subject":"trade.l3open","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:50.123       {"data":{"sequence":"1553507769499","symbol":"KCS-BTC","reason":"canceled","side":"buy","size":"11.0508","orderId":"5c9bae17cdaba45ba946195f","price":"0.00032858000000000000","time":"1553706530100963115","type":"done"},"subject":"trade.l3done","topic":"/market/level3:KCS-BTC","type":"message"}
2019.03.27 20:08:50.123       [DONE CANCELED] KCS-BTC price 0.00032858000000000000 not found in the book (BUY)
--- DONE received but requested book doesn't contains price 0.00032858 & order id 5c9bae17cdaba45ba946195f

**Comment by mingyangwang** [comment]
It may be caused by a lost message.

**Comment by mingyangwang** [comment]
But we have fixed the problem in the orderbook

**Comment by augenblicke** [comment]
Yes, thank you!

The problem is not that the message was missed, but that after requesting the book the missing message (order) is also missing in the requested book, and this is not because the DONE message was lost too - DONE message will be sent after a some time (seconds, minutes or hours)

But it is more strange that almost all losses happen with OPEN message that follows RECEIVED

**Comment by augenblicke** [comment]
RECEIVED -> missing OPEN -> MATCH or DONE

**Comment by mingyangwang** [comment]
For first question, the done message is slow to update because it needs to wait for the transaction. For second question, the stop loss order is updated in the open message because the stop loss order is not an order, at least before it is triggered.
