### ISSUE TITLE
Wrong sequence of HOT-ETH level3 book

### ISSUE THREAD

**Issue by augenblicke** [Kucoin/kucoin-api-docs#65]
HOT-ETH book request (/api/v1/market/orderbook/level3?symbol=HOT-ETH) always returns the book with constantly the same sequence = 1553507384872

Meanwhile, the socket messages come normally (incremented) and their sequences have much larger value (about 370245400 larger)

2019.04.01 15:15:57.964   {"data":{"sequence":"1553877630272","symbol":"HOT-ETH","reason":"canceled","side":"buy","size":"2719.2417","orderId":"5ca200b7c788c66106d8bafc","price":"0.00020874000000000000","time":"1554120957924842124","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:57.969   [1] HOT-ETH book msg sequence missed 370245399 messages (1553507384872 ... 1553877630272)
2019.04.01 15:15:57.969   calibrating HOT-ETH book...
2019.04.01 15:15:57.984   {"data":{"sequence":"1553877630273","symbol":"HOT-ETH","orderType":"limit","side":"buy","size":"2719.2417","orderId":"5ca200fd054b467df58a6213","price":"0.00020873000000000000","time":"1554120957955297564","type":"received","clientOid":"17449354"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:57.984   {"data":{"sequence":"1553877630274","symbol":"HOT-ETH","side":"buy","size":"2719.2417","orderId":"5ca200fd054b467df58a6213","price":"0.00020873000000000000","time":"1554120957955297564","type":"open","remainSize":"2719.2417"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:58.247   {"data":{"sequence":"1553877630275","symbol":"HOT-ETH","reason":"canceled","side":"buy","size":"2990.9502","orderId":"5ca200b70bad454a9ac7f48a","price":"0.00020456000000000000","time":"1554120958203800573","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:58.328   {"data":{"sequence":"1553877630276","symbol":"HOT-ETH","orderType":"limit","side":"buy","size":"2990.9502","orderId":"5ca200fe4c06872e796e00c5","price":"0.00020455000000000000","time":"1554120958297774542","type":"received","clientOid":"17449355"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:58.328   {"data":{"sequence":"1553877630277","symbol":"HOT-ETH","side":"buy","size":"2990.9502","orderId":"5ca200fe4c06872e796e00c5","price":"0.00020455000000000000","time":"1554120958297774542","type":"open","remainSize":"2990.9502"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:58.550   {"data":{"sequence":"1553877630278","symbol":"HOT-ETH","reason":"canceled","side":"buy","size":"3289.8081","orderId":"5ca200b75137b95c6fb859e0","price":"0.00020039000000000000","time":"1554120958504865190","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:58.672   {"data":{"sequence":"1553877630279","symbol":"HOT-ETH","orderType":"limit","side":"buy","size":"3289.8081","orderId":"5ca200fe0bad454a9ac7fc33","price":"0.00020038000000000000","time":"1554120958629492072","type":"received","clientOid":"17449356"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:58.672   {"data":{"sequence":"1553877630280","symbol":"HOT-ETH","side":"buy","size":"3289.8081","orderId":"5ca200fe0bad454a9ac7fc33","price":"0.00020038000000000000","time":"1554120958629492072","type":"open","remainSize":"3289.8081"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:58.834   {"data":{"sequence":"1553877630281","symbol":"HOT-ETH","reason":"canceled","side":"sell","size":"2705.4864","orderId":"5ca200b80bad454a9ac7f497","price":"0.00021275000000000000","time":"1554120958785803550","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:59.036   {"data":{"sequence":"1553877630282","symbol":"HOT-ETH","orderType":"limit","side":"sell","size":"2705.4864","orderId":"5ca200fe0bad453fa29663b6","price":"0.00021274000000000000","time":"1554120958991325798","type":"received","clientOid":"17449357"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:59.036   {"data":{"sequence":"1553877630283","symbol":"HOT-ETH","side":"sell","size":"2705.4864","orderId":"5ca200fe0bad453fa29663b6","price":"0.00021274000000000000","time":"1554120958991325798","type":"open","remainSize":"2705.4864"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:59.116   {"data":{"sequence":"1553877630284","symbol":"HOT-ETH","reason":"canceled","side":"sell","size":"2990.0249","orderId":"5ca200b8cdaba4647d11a90a","price":"0.00021701000000000000","time":"1554120959074380124","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:59.359   {"data":{"sequence":"1553877630285","symbol":"HOT-ETH","orderType":"limit","side":"sell","size":"2990.0249","orderId":"5ca200ffcdaba4647d11b129","price":"0.00021700000000000000","time":"1554120959324491948","type":"received","clientOid":"17449358"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:59.359   {"data":{"sequence":"1553877630286","symbol":"HOT-ETH","side":"sell","size":"2990.0249","orderId":"5ca200ffcdaba4647d11b129","price":"0.00021700000000000000","time":"1554120959324491948","type":"open","remainSize":"2990.0249"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:59.419   {"data":{"sequence":"1553877630287","symbol":"HOT-ETH","reason":"canceled","side":"sell","size":"3304.4886","orderId":"5ca200b889fc84505901b0a0","price":"0.00022126000000000000","time":"1554120959376442481","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:59.682   {"data":{"sequence":"1553877630288","symbol":"HOT-ETH","orderType":"limit","side":"sell","size":"3304.4886","orderId":"5ca200ff0bad453fa29663bf","price":"0.00022125000000000000","time":"1554120959654249187","type":"received","clientOid":"17449359"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:59.702   {"data":{"sequence":"1553877630289","symbol":"HOT-ETH","side":"sell","size":"3304.4886","orderId":"5ca200ff0bad453fa29663bf","price":"0.00022125000000000000","time":"1554120959654249187","type":"open","remainSize":"3304.4886"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:15:59.756   [2] HOT-ETH book msg sequence missed 370245400 messages (1553507384872 ... 1553877630273)
2019.04.01 15:15:59.756   calibrating HOT-ETH book...
2019.04.01 15:16:01.530   HOT-ETH book successfully calibrated   requested book sequence: 1553507384872
2019.04.01 15:17:31.695   {"data":{"sequence":"1553877630290","symbol":"HOT-ETH","reason":"canceled","side":"buy","size":"2719.2417","orderId":"5ca200fd054b467df58a6213","price":"0.00020873000000000000","time":"1554121051660949227","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:31.695   [3] HOT-ETH book msg sequence missed 370245417 messages (1553507384872 ... 1553877630290)
2019.04.01 15:17:31.695   calibrating HOT-ETH book...
2019.04.01 15:17:31.978   {"data":{"sequence":"1553877630291","symbol":"HOT-ETH","reason":"canceled","side":"buy","size":"2990.9502","orderId":"5ca200fe4c06872e796e00c5","price":"0.00020455000000000000","time":"1554121051947338147","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:32.284   {"data":{"sequence":"1553877630292","symbol":"HOT-ETH","reason":"canceled","side":"buy","size":"3289.8081","orderId":"5ca200fe0bad454a9ac7fc33","price":"0.00020038000000000000","time":"1554121052241744746","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:32.525   {"data":{"sequence":"1553877630293","symbol":"HOT-ETH","orderType":"limit","side":"buy","size":"2719.2417","orderId":"5ca2015c5137b95c6fb86c9f","price":"0.00020872000000000000","time":"1554121052491505126","type":"received","clientOid":"17449405"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:32.526   {"data":{"sequence":"1553877630294","symbol":"HOT-ETH","side":"buy","size":"2719.2417","orderId":"5ca2015c5137b95c6fb86c9f","price":"0.00020872000000000000","time":"1554121052491505126","type":"open","remainSize":"2719.2417"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:32.566   {"data":{"sequence":"1553877630295","symbol":"HOT-ETH","reason":"canceled","side":"sell","size":"2705.4864","orderId":"5ca200fe0bad453fa29663b6","price":"0.00021274000000000000","time":"1554121052531785002","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:32.848   {"data":{"sequence":"1553877630296","symbol":"HOT-ETH","reason":"canceled","side":"sell","size":"2990.0249","orderId":"5ca200ffcdaba4647d11b129","price":"0.00021700000000000000","time":"1554121052813445262","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:32.868   {"data":{"sequence":"1553877630297","symbol":"HOT-ETH","orderType":"limit","side":"buy","size":"2990.9502","orderId":"5ca2015c0bad454a9ac806d9","price":"0.00020454000000000000","time":"1554121052823977695","type":"received","clientOid":"17449406"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:32.869   {"data":{"sequence":"1553877630298","symbol":"HOT-ETH","side":"buy","size":"2990.9502","orderId":"5ca2015c0bad454a9ac806d9","price":"0.00020454000000000000","time":"1554121052823977695","type":"open","remainSize":"2990.9502"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:33.151   {"data":{"sequence":"1553877630299","symbol":"HOT-ETH","reason":"canceled","side":"sell","size":"3304.4886","orderId":"5ca200ff0bad453fa29663bf","price":"0.00022125000000000000","time":"1554121053115942149","type":"done"},"subject":"trade.l3done","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:33.233   {"data":{"sequence":"1553877630300","symbol":"HOT-ETH","orderType":"limit","side":"buy","size":"3289.8081","orderId":"5ca2015d0bad454a9ac806e4","price":"0.00020037000000000000","time":"1554121053188383275","type":"received","clientOid":"17449407"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:33.233   {"data":{"sequence":"1553877630301","symbol":"HOT-ETH","side":"buy","size":"3289.8081","orderId":"5ca2015d0bad454a9ac806e4","price":"0.00020037000000000000","time":"1554121053188383275","type":"open","remainSize":"3289.8081"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:33.535   [4] HOT-ETH book msg sequence missed 370245418 messages (1553507384872 ... 1553877630291)
2019.04.01 15:17:33.535   calibrating HOT-ETH book...
2019.04.01 15:17:33.576   {"data":{"sequence":"1553877630302","symbol":"HOT-ETH","orderType":"limit","side":"sell","size":"2705.4864","orderId":"5ca2015d89fc84505901c305","price":"0.00021273000000000000","time":"1554121053532754852","type":"received","clientOid":"17449408"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:33.576   {"data":{"sequence":"1553877630303","symbol":"HOT-ETH","side":"sell","size":"2705.4864","orderId":"5ca2015d89fc84505901c305","price":"0.00021273000000000000","time":"1554121053532754852","type":"open","remainSize":"2705.4864"},"subject":"trade.l3open","topic":"/market/level3:HOT-ETH","type":"message"}
2019.04.01 15:17:33.900   {"data":{"sequence":"1553877630304","symbol":"HOT-ETH","orderType":"limit","side":"sell","size":"2990.0249","orderId":"5ca2015dcdaba45e0b6cccec","price":"0.00021699000000000000","time":"1554121053873805118","type":"received","clientOid":"17449409"},"subject":"trade.l3received","topic":"/market/level3:HOT-ETH","type":"message"}

**Comment by ZhangReeta** [comment]
We have restarted the order book of the HOT-ETH due to the consumption blocking of kafka, and you can try again.
